services:
  tg_bot:
    image: "nkodenko/ods-acd-tg-bot:latest"
    restart: always
    pull_policy: always
    configs:
      - source: tg_bot_config
        target: /app/config.yml
  predictor:
    image: "nkodenko/ods-acd-predictor:latest"
    restart: always
    pull_policy: always
    # uncomment for debugging:
    # ports:
    #   - "8080:8080"
    environment:
      DISABLE_MODEL: 0
      VECTORIZER_PATH: "/data/tfidf.joblib"
      MODEL_PATH:  "/data/logreg.joblib"
    volumes:
      - type: bind
        source: ./predictor/data
        target: /data
configs:
  tg_bot_config:
    file: ./tg-bot/config.yml
