name: Build Docker images
on:
  push:
    branches:
      - master
      # TODO: rm after testing
      - ci-cd-tg-bot-img
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nkodenko/ods-acd-tg-bot
          tags:
            type=raw,value=latest,enable=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: serverapp/tg-bot
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
