name: Build Docker images
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push tg-bot Docker image
        uses: docker/build-push-action@v2
        with:
          context: serverapp/tg-bot
          push: true
          tags: nkodenko/ods-acd-tg-bot:latest
      - name: Build and push predictor Docker image
        uses: docker/build-push-action@v2
        with:
          context: serverapp/predictor
          push: true
          tags: nkodenko/ods-acd-predictor:latest

